name: worldcup-ticketing-api
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - mariadb/.env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
